nombres = ["Ana","Antonio","Ana","Jose","Carlos"]
nombres.append("Aby")
print(nombres)
nombres.insert(int(input("Posicion: ")),input("Nombre Nuevo: "))
print(nombres)
posicion = int(input())
nombres[posicion] = input("Nombre Nuevo: ")
print(nombres)
nombres[int(input("Posicion: "))] = input("Nombre Nuevo: ")
print(nombres)
nombres.remove("Carlos")
print(nombres)
nombre_borrado = nombres.pop(3)
print(f"Nombre borrado: {nombre_borrado}")
print(nombres)
nombres.reverse()
print(nombres)
nombres.remove("Ana")